# Generated by Django 4.2.6 on 2023-10-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_userstock_max_price_alter_userstock_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
