# Generated by Django 4.2.6 on 2023-10-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_userstock_max_price_alter_userstock_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='periodicity',
            field=models.CharField(default='5m', max_length=3, null=True),
        ),
    ]
