# Generated by Django 4.2.6 on 2023-10-11 02:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('interval', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('close_price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('high_price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('low_price', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('volume', models.IntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_fetcher.stock')),
            ],
        ),
    ]
