# Generated by Django 4.2.6 on 2023-10-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_fetcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='interval',
        ),
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
