# Generated by Django 4.2.6 on 2023-10-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_fetcher', '0003_alter_stock_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
