# Generated by Django 4.2.6 on 2023-10-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_fetcher', '0004_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
