# Generated by Django 4.2.6 on 2023-10-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_fetcher', '0006_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
