# Generated by Django 4.2.6 on 2023-10-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_fetcher', '0007_alter_stock_current_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['ticker']},
        ),
    ]
